/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectsSlugRouteImport } from './routes/projects_.$slug'
import { Route as ApiDriveImageFileIdRouteImport } from './routes/api/drive-image/$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects_/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveImageFileIdRoute = ApiDriveImageFileIdRouteImport.update({
  id: '/api/drive-image/$fileId',
  path: '/api/drive-image/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/faq': typeof FaqRoute
  '/get-involved': typeof GetInvolvedRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/drive-image/$fileId': typeof ApiDriveImageFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/faq': typeof FaqRoute
  '/get-involved': typeof GetInvolvedRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/drive-image/$fileId': typeof ApiDriveImageFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/faq': typeof FaqRoute
  '/get-involved': typeof GetInvolvedRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRoute
  '/projects_/$slug': typeof ProjectsSlugRoute
  '/api/drive-image/$fileId': typeof ApiDriveImageFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/faq'
    | '/get-involved'
    | '/news'
    | '/projects'
    | '/projects/$slug'
    | '/api/drive-image/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/faq'
    | '/get-involved'
    | '/news'
    | '/projects'
    | '/projects/$slug'
    | '/api/drive-image/$fileId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/faq'
    | '/get-involved'
    | '/news'
    | '/projects'
    | '/projects_/$slug'
    | '/api/drive-image/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  FaqRoute: typeof FaqRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  NewsRoute: typeof NewsRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ApiDriveImageFileIdRoute: typeof ApiDriveImageFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$slug': {
      id: '/projects_/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive-image/$fileId': {
      id: '/api/drive-image/$fileId'
      path: '/api/drive-image/$fileId'
      fullPath: '/api/drive-image/$fileId'
      preLoaderRoute: typeof ApiDriveImageFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  FaqRoute: FaqRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  NewsRoute: NewsRoute,
  ProjectsRoute: ProjectsRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ApiDriveImageFileIdRoute: ApiDriveImageFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
